import './globals.css'
import { Roboto } from 'next/font/google'
import Footer from "@/features/footer/ui/footer";
import Header from "@/features/header/ui/footer";
import Navbar from "@/features/navbar/ui/navbar";
import {Container} from "@mui/material";

const roboto = Roboto({
    subsets: ["cyrillic"],
    weight: ["400", "500", "300"]
})

export const metadata = {
  title: 'Test Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        <Navbar/>
        <main>
            <Container maxWidth="lg">
                {children}
            </Container>
        </main>
        <Footer/>
      </body>
    </html>
  )
}
