import './globals.css'
import { Inter } from 'next/font/google'
import Footer from "@/features/footer/ui/footer";
import Header from "@/features/header/ui/footer";
import Navbar from "@/features/navbar/ui/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
